version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:cached
      - ./data:/app/data
    environment:
      - AMZ_DB_PATH=/app/data/db/reviews.db
      - AMZ_EXPORT_CSV=/app/data/export/reviews_for_dashboard.csv
    restart: unless-stopped