version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:cached
    environment:
      - AMZ_DB_PATH=data/db/reviews.db
      - AMZ_RAW_CSV=data/raw/reviews.csv
      - AMZ_EXPORT_CSV=data/export/reviews_for_dashboard.csv
